Fix GA_KEY_CONTENT OpenSSL crypto error
OpenSSL.crypto.load_privatekey can't detect start line due to a
str.replace() for '\n' and '\r'.
json.loads() can't handle '\n' and '\r' cause it thinks they are
control character.
Therefore '\n' and '\r' have to be double escape rather than deleted.
OpenSSL.crypto.load_privatekey() can't handle '\r' either,
so a private_key with '\r' wouldn't work anyway. ¯\_(ツ)_/¯

Error:
OpenSSL.crypto.Error: [('PEM routines', 'get_name', 'no start line')]

Ref:
tomdyson#25
https://stackoverflow.com/a/45571017